// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://jvoonedaanehoasaawvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2b29uZWRhYW5laG9hc2Fhd3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNzEwNDIsImV4cCI6MjA3NTc0NzA0Mn0.B6wgDhpWn1Soafcvjkl4Rm36rTfgrlhd7PUgkDrgXhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);